### ISSUE TITLE
On mobile phone the slider doesn't slide

### ISSUE THREAD

**Issue by ghost** [domsleee/JQuery-Range-Slider#3]
On my android phone the demo doesn't work at all and my own implementation only works when tapping (and not sliding). It works the same when I'm using chrome's built in device toolbar where you can display how the page would look on a smaller device. Even the tapping is very inconsistent and doesn't always register.

**Comment by domsleee** [comment]
Yo,

Seems like the touch events weren't bound properly. See #4

**Comment by ghost** [comment]
Thank you for the quick fix. Works perfectly now!
